[package]
name = "enigma"
version = "0.1.0"
authors = ["Jonathan Boyd"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0", features = ["derive"] }
anyhow = { version = "1.0.63"}